/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto_fase1_zea_1168522_izaguirre_1170522;

import static java.awt.image.ImageObserver.WIDTH;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.security.SecureRandom;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Base64;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import javax.crypto.Cipher;
import javax.crypto.spec.IvParameterSpec;
import javax.crypto.spec.SecretKeySpec;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Mario
 */
public class MENU extends javax.swing.JFrame {

    /**
     * Creates new form MENU
     */
    String usuarioGlo;
    Operador op = new Operador();
    public MENU() {
        initComponents();
    }

    public MENU(String usuario)
    {
        initComponents();
        //se escribe en pantalla
        labelUsuario.setText("Usuario: " + usuario.split("\\|")[0]);
        labelNombre.setText("Nombre: " + usuario.split("\\|")[1]);
        labelApellido.setText("Apellido: " + usuario.split("\\|")[2]);
        labelFecha.setText("Nació el: " + usuario.split("\\|")[5]);
        labelCorreo.setText("Correo: " + usuario.split("\\|")[6]);
        labelNum.setText("Teléfono: " + usuario.split("\\|")[7]);
        op.SetImageLabel(LabelFoto, usuario.split("\\|")[8], this);
        //se guarda el usuario
        usuarioGlo = usuario;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        labelUsuario = new javax.swing.JLabel();
        labelApellido = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelFecha = new javax.swing.JLabel();
        labelCorreo = new javax.swing.JLabel();
        labelNum = new javax.swing.JLabel();
        btncerrarsesion = new javax.swing.JButton();
        LabelFoto = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        textBoxContraseña = new javax.swing.JTextPane();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        textBoxCorreo = new javax.swing.JTextPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        textBoxUsuario = new javax.swing.JTextPane();
        labelEstado = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        textBoxTelefono = new javax.swing.JTextPane();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        botonListo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        textBoxNombre = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        textBoxRutaFoto = new javax.swing.JTextPane();
        botonFoto = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        textBoxApellido = new javax.swing.JTextPane();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        textBoxFecha = new javax.swing.JTextPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        btnborrarusuario = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        txtborrarusuario = new javax.swing.JTextPane();
        jLabel19 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        btnhaceradmin = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        txtadminusuario = new javax.swing.JTextPane();
        jPanel6 = new javax.swing.JPanel();
        botonCambio = new javax.swing.JButton();
        jScrollPane12 = new javax.swing.JScrollPane();
        textBoxCambioRutaFoto = new javax.swing.JTextPane();
        botonFoto1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        textBoxCambioFecha = new javax.swing.JTextPane();
        jScrollPane14 = new javax.swing.JScrollPane();
        textBoxCambioTelefono = new javax.swing.JTextPane();
        jScrollPane15 = new javax.swing.JScrollPane();
        textBoxCambioUsuario = new javax.swing.JTextPane();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane16 = new javax.swing.JScrollPane();
        textBoxCambioCorreo = new javax.swing.JTextPane();
        jLabel7 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel1.setText("PAGINA PRINCIPAL:");

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 607, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(153, 153, 153));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel3.setFont(new java.awt.Font("Gadugi", 0, 24)); // NOI18N
        jLabel3.setText("PAGINA PRINCIPAL:");

        labelUsuario.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        labelUsuario.setText("Usuario:");

        labelApellido.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        labelApellido.setText("Apellido:");

        labelNombre.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        labelNombre.setText("Nombre: ");

        labelFecha.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        labelFecha.setText("Fecha de Nacimiento: ");

        labelCorreo.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        labelCorreo.setText("Correo: ");

        labelNum.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        labelNum.setText("Número de teléfono: ");

        btncerrarsesion.setBackground(new java.awt.Color(153, 204, 255));
        btncerrarsesion.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        btncerrarsesion.setForeground(new java.awt.Color(0, 0, 0));
        btncerrarsesion.setText("Cerrar Sesión");
        btncerrarsesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncerrarsesionActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(153, 204, 255));
        jButton2.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Condensar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
                    .addComponent(labelApellido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelCorreo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(labelUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelNum, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btncerrarsesion, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                    .addComponent(LabelFoto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelUsuario)
                        .addGap(14, 14, 14)
                        .addComponent(labelNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelApellido)
                        .addGap(18, 18, 18)
                        .addComponent(labelFecha))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(LabelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelCorreo)
                        .addGap(14, 14, 14)
                        .addComponent(labelNum))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btncerrarsesion, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Menu Principal", jPanel1);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jScrollPane4.setViewportView(textBoxContraseña);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Para registrarte, necesitamos que llenes todos los campos y que no dejes ninguno vacío");

        jLabel10.setText("eMail: (no te excedas de los 40 caracteres)");

        jLabel11.setText("Usuario: (no te excedas de los 20 caracteres");

        jLabel12.setText("Contraseña: (no te excedas de los 40 caracteres)");

        jScrollPane8.setViewportView(textBoxCorreo);

        jScrollPane1.setViewportView(textBoxUsuario);

        labelEstado.setText("Estado: en proceso");

        jScrollPane5.setViewportView(textBoxTelefono);

        jLabel13.setText("Teléfono");

        jLabel14.setText("Nombre: (no te excedas de los 30 caracteres");

        botonListo.setBackground(new java.awt.Color(153, 204, 255));
        botonListo.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        botonListo.setForeground(new java.awt.Color(0, 0, 0));
        botonListo.setText("¡Listo!");
        botonListo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonListoActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(textBoxNombre);

        textBoxRutaFoto.setEnabled(false);
        jScrollPane6.setViewportView(textBoxRutaFoto);

        botonFoto.setBackground(new java.awt.Color(153, 204, 255));
        botonFoto.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        botonFoto.setForeground(new java.awt.Color(0, 0, 0));
        botonFoto.setText("Examinar...");
        botonFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFotoActionPerformed(evt);
            }
        });

        jLabel15.setText("Apellido: (no te excedas de los 30 caracteres)");

        jLabel16.setText("Fecha de nacimiento: (d/m/a)");

        jScrollPane3.setViewportView(textBoxApellido);

        jLabel17.setText("Foto de perfil");

        jScrollPane7.setViewportView(textBoxFecha);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel11)
                                .addComponent(jScrollPane1))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(botonListo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(165, 165, 165)
                                .addComponent(botonFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(98, 149, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelEstado)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonListo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Crear Usuario", jPanel2);

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        jLabel18.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        jLabel18.setText("Busca el usuario que deseas dar de baja.");

        btnborrarusuario.setBackground(new java.awt.Color(153, 204, 255));
        btnborrarusuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnborrarusuario.setForeground(new java.awt.Color(0, 0, 0));
        btnborrarusuario.setText("Borrar Usuario");
        btnborrarusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnborrarusuarioActionPerformed(evt);
            }
        });

        jScrollPane9.setViewportView(txtborrarusuario);

        jLabel19.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        jLabel19.setText("Buscar Usuario");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnborrarusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(177, 177, 177))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addGap(115, 115, 115)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnborrarusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Borrar Usuario", jPanel3);

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));

        jLabel20.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        jLabel20.setText("Buscar Usuario");

        btnhaceradmin.setBackground(new java.awt.Color(153, 204, 255));
        btnhaceradmin.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        btnhaceradmin.setForeground(new java.awt.Color(0, 0, 0));
        btnhaceradmin.setText("Hacer admin");
        btnhaceradmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhaceradminActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        jLabel21.setText("Busca el usuario que desea hacer admin");

        jScrollPane10.setViewportView(txtadminusuario);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(203, 203, 203))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(btnhaceradmin, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(190, 190, 190))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addGap(66, 66, 66)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnhaceradmin, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(146, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Admin", jPanel5);

        jPanel6.setBackground(new java.awt.Color(153, 153, 153));

        botonCambio.setBackground(new java.awt.Color(153, 204, 255));
        botonCambio.setForeground(new java.awt.Color(0, 0, 0));
        botonCambio.setText("Cambiar");
        botonCambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCambioActionPerformed(evt);
            }
        });

        textBoxCambioRutaFoto.setEnabled(false);
        jScrollPane12.setViewportView(textBoxCambioRutaFoto);

        botonFoto1.setBackground(new java.awt.Color(153, 204, 255));
        botonFoto1.setForeground(new java.awt.Color(0, 0, 0));
        botonFoto1.setText("Examinar...");
        botonFoto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFoto1ActionPerformed(evt);
            }
        });

        jLabel8.setText("Foto de perfil");

        jLabel2.setText("Correo");

        jLabel4.setText("Teléfono");

        jLabel5.setText("Cumpleaños");

        jScrollPane13.setViewportView(textBoxCambioFecha);

        jScrollPane14.setViewportView(textBoxCambioTelefono);

        jScrollPane15.setViewportView(textBoxCambioUsuario);

        jLabel6.setText("d/m/a");

        jScrollPane16.setViewportView(textBoxCambioCorreo);

        jLabel7.setText("Usuario");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                        .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(67, 67, 67)))
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(28, 28, 28))))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(botonFoto1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 89, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(jLabel7)))
                                .addGap(78, 78, 78)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(botonCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(156, 156, 156)))))
                .addGap(57, 57, 57))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel6)
                        .addGap(3, 3, 3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonFoto1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(29, 29, 29)
                .addComponent(botonCambio)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cambiar datos", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncerrarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncerrarsesionActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Gracias por usar nuestra red! vuelva pronto",  "Gracias!", WIDTH);
        new Inicio().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btncerrarsesionActionPerformed

    private void botonListoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonListoActionPerformed
        
    }//GEN-LAST:event_botonListoActionPerformed

    private void botonFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFotoActionPerformed

    }//GEN-LAST:event_botonFotoActionPerformed

    private void btnborrarusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnborrarusuarioActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnborrarusuarioActionPerformed

    private void btnhaceradminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhaceradminActionPerformed

    }//GEN-LAST:event_btnhaceradminActionPerformed

    private void botonCambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCambioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCambioActionPerformed

    private void botonFoto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFoto1ActionPerformed
        // TODO add your handling code here:
        String ruta;
        ruta = op.obtenerNuevaRutaImg(this);
        if(ruta == null)
        {
            textBoxRutaFoto.setText("");
        }
        else
        {
            textBoxRutaFoto.setText(op.duplicarImagen(ruta));
        }
    }//GEN-LAST:event_botonFoto1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    public static String cifrar(String key, String value) {
        try {
            // Generar IV seguro
            SecureRandom random = new SecureRandom();
            byte[] iv = new byte[16];
            random.nextBytes(iv);
            IvParameterSpec ivParameterSpec = new IvParameterSpec(iv);

            // Configurar clave y cifrador
            SecretKeySpec skeySpec = new SecretKeySpec(key.getBytes("UTF-8"), "AES");
            Cipher cipher = Cipher.getInstance("AES/CBC/PKCS5PADDING");
            cipher.init(Cipher.ENCRYPT_MODE, skeySpec, ivParameterSpec);

            // Cifrar el valor
            byte[] encrypted = cipher.doFinal(value.getBytes("UTF-8"));

            // Concatenar IV y texto cifrado para facilitar la decodificación
            byte[] ivAndEncrypted = new byte[iv.length + encrypted.length];
            System.arraycopy(iv, 0, ivAndEncrypted, 0, iv.length);
            System.arraycopy(encrypted, 0, ivAndEncrypted, iv.length, encrypted.length);

            // Codificar en Base64 para obtener una cadena segura
            return Base64.getEncoder().encodeToString(ivAndEncrypted);
        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;
    }

    public static String descifrar(String key, String initVector, String encrypted) {
        try {
            IvParameterSpec iv = new IvParameterSpec(initVector.getBytes("UTF-8"));
            SecretKeySpec skeySpec = new SecretKeySpec(key.getBytes("UTF-8"), "AES");

            Cipher cipher = Cipher.getInstance("AES/CBC/PKCS5PADDING");
            cipher.init(Cipher.DECRYPT_MODE, skeySpec, iv);

            byte[] original = cipher.doFinal(Base64.getDecoder().decode(encrypted));

            return new String(original);
        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;
    }
    
    private void realizarBackup(String rutaOrigen, String rutaDestino, String nombreNuevoArchivo, String strError) {
    try 
    {
        // Lee el contenido del archivo en rutaOrigen
        List<String> contenido = Obtener(rutaOrigen, strError);
        // Crea el nuevo archivo en la carpeta especificada
        String rutaNuevoArchivo = rutaDestino + File.separator + nombreNuevoArchivo;
        escribirLista(contenido, rutaNuevoArchivo, strError);
    } 
    catch (Exception e) 
    {
        JOptionPane.showMessageDialog(this, "Error al realizar el backup", "Error", JOptionPane.ERROR_MESSAGE);
    }
}
    
    public void escribirLista(List<String> lista, String ruta, String strError)
    {
        for (int i = 0; i < lista.size(); i++) 
        {
            LlenarArchivo(ruta, lista.get(i), strError);
        }
    }
    
    public boolean LlenarArchivo(String strPath,String strContenido,String strError)
    {
        File Archivo = new File(strPath);
        
        try
        {
                FileWriter Escribir = new FileWriter(Archivo,true);
                BufferedWriter bw = new BufferedWriter(Escribir);
                bw.write(strContenido+ System.getProperty( "line.separator" ));
                bw.close();
                Escribir.close();
                
                return true;
        }
        catch(IOException ex)
        {
            strError= ex.getMessage();
            return false;
        } 
        
    }
    
    private static boolean borrarContenidoArchivo(String strPath) {
        try {
            // Abre el archivo en modo de escritura sin añadir contenido (append = false)
            FileWriter escribir = new FileWriter(strPath, false);
            escribir.close();
            return true;
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "No",  "non", WIDTH);
            return false;
        }
    }
    
    public List<String> Obtener(String strPath,String strError)
    {
        //variable tipo archivo (en este caso es un txt)
        File Archivo = new File(strPath);
        //si se encuentra el archivo en la ruta indicada, pasa
        if(Archivo.exists()==true)
        {
            //se crea la lista a enviar
            List<String> ListaPunteo = new ArrayList<>();
            //se crea la variable que nos leerá el archivo
            FileReader LecturaArchivo;
            //try/cacht en caso que el archivo enviado no sea el indicado
            try {
                //se le envía el archivo a leer al lector
                LecturaArchivo = new FileReader(Archivo);
                //búfer de datos
                BufferedReader LeerArchivo = new BufferedReader(LecturaArchivo);
                //string que me guarda el texto por línea
                String Linea;
                //try/catch en caso que se envíe un archivo que no es el solicitado
                try 
                {
                    //la variable "Linea" adquiere el valor de la primera línea del archivo
                    Linea=LeerArchivo.readLine();
                    //se crea otro string donde se va a almacenar el texto por cada línea del archivo
                    String modeloNum = ""; 
                    //ciclo para leer linea por linea el archivo, mientras que la linea no sea null (no haya llegado al final del archivo), se repetirá el ciclo
                    while(Linea != null)
                    {
                        //si en la línea hay texto, se escribe
                        if(!"".equals(Linea))
                        {
                            //la variable modeloNum, adquiere el valor de lo que está en la línea que se está leyendo
                            modeloNum = Linea;
                        }
                        //se agrega ese modelo a la lista
                        ListaPunteo.add(modeloNum);
                        //pasa a la siguiente línea para que el ciclo continue 
                        Linea=LeerArchivo.readLine();
                    }
                    //se cierra el archivo
                    LecturaArchivo.close();
                    //se termina de leer
                    LeerArchivo.close();
                    //no habrá mensaje de error
                    strError="";
                    //se retorna la lista ya llena
                    return ListaPunteo;
                    
                }
                //catch para mostrar el mensaje de error
                catch (IOException ex) 
                {
                    //mensaje de error
                    strError= ex.getMessage();
                    //la lista se retorna nula
                    return null;
                }
            } 
            //catch para mostrar el mensaje de error
            catch (FileNotFoundException ex) 
            {
                //mensaje de error
                strError= ex.getMessage();
                //la lista se retorna nula
                return null;
            }            
        }
        //si el archivo no se encuentra en la ruta indicada, se muestra un mensaje de error y la lista que se envía estará vacía
        else
        {
            //mensaje de error
            strError="No existe el archivo";
            //lista nula
            return null;
        }
    }
    
    private static int buscarPorCriterio(List<String> lista, String criterio) 
    {
        for (int i = 0; i < lista.size(); i++) 
        {
            String[] partes = lista.get(i).split("\\|");
            if (partes.length > 0 && partes[0].equals(criterio) && partes[9].equals("1")) 
            {
                return i;
            }
        }
        return -1;  // No se encontró el elemento
    }
    
    public int punt(String cod, List<String> punteos)
    {
        //variable que guarda la puntuación final
        int puntu = 0;
        //puntuación va a ser igual a segundo número por el total de caracteres de la contraseña
        puntu = puntu + (cod.length() * Integer.parseInt(punteos.get(1)));
        //se crea la variable que guarde la cantidad de mayusculas en el string
        int mayus = 0;
        //se crea la variable que guarde la cantidad de letras en el string
        int letras = 0;
        //se crea la variable que guarde la cantidad de numeros en el string
        int nums = 0;
        //se crea la variable que guarde la cantidad de caracteres especiales en el string
        int especiales = 0;
        //se crea la variable que compruebe si solo hay letras
        boolean soloLetras = true;
        //se crea la variable que compruebe si solo hay numeros
        boolean soloNums = true;
        //ciclo para recorrer cada caracter del string
        for (char caracter : cod.toCharArray()) 
        {
            //se comprueba si el caracter está en mayuscula o no
            if(Character.isUpperCase(caracter))
            {
                //en caso que si, se le suma a la variable
                mayus++;
            }
            //se comprueba si el caracter es letra o no
            if(Character.isLetter(caracter))
            {
                //en caso que si, se agrega una unidad al contador
                letras++;
                //si hay por lo menos 1 letra significa que no hay solo numeros, por lo tanto se vuelve falso
                soloNums = false;
            }
            //se comprueba si el caracter es letra o no
            if(Character.isDigit(caracter))
            {
                //en caso que si, se agrega una unidad al contador
                nums++;
                //si hay por lo menos 1 numero significa que no hay solo letras, por lo tanto se vuelve falso
                soloLetras = false;
            }
            //se comprueba si el caracter es especial o no (si pertenece a /¿?%$#)
            if(caracter == '/' || caracter == '¿' || caracter == '?' || caracter == '%' || caracter == '$' || caracter == '#')
            {
                //en caso que si, se agrega una unidad al contador
                especiales++;
                //si hay por lo menos 1 especial significa que no hay solo numeros o solo letras, por lo tanto se vuelven falsos
                soloNums = false;
                soloLetras = false;
            }
        }
        //se calcula nuevamente la puntuación (tomando en cuenta solo mayúsculas
        puntu = puntu + (mayus * Integer.parseInt(punteos.get(2)));
        //se calcula nuevamente la puntuación (tomando en cuenta solo si son letras
        puntu = puntu + (letras + Integer.parseInt(punteos.get(3)));
        //se calcula nuevamente la puntuación (tomando en cuenta solo si son numeros
        puntu = puntu + (nums + Integer.parseInt(punteos.get(4)));
        //se calcula nuevamente la puntuación (tomando en cuenta solo si son numeros
        puntu = puntu + (especiales *( cod.length()+ Integer.parseInt(punteos.get(5))));
        //si solo hay letras se hace la resta
        if(soloLetras)
        {
            //si solo hay letras, se hace la resta
            puntu = puntu - Integer.parseInt(punteos.get(6));
        }
        //si solo hay numeros se hace la resta
        if(soloNums)
        {
            puntu = puntu - Integer.parseInt(punteos.get(7));
        }
        //se retorna el punteo
        return puntu;
    }
    
    public int comprobar(String strPath,String strError)
    {
        //variable tipo archivo (en este caso es un txt)
        File Archivo = new File(strPath);
        //si se encuentra el archivo en la ruta indicada, pasa
        if(Archivo.exists()==true)
        {
            //se crea la variable que nos leerá el archivo
            FileReader LecturaArchivo;
            //try/cacht en caso que el archivo enviado no sea el indicado
            try {
                //se le envía el archivo a leer al lector
                LecturaArchivo = new FileReader(Archivo);
                //búfer de datos
                BufferedReader LeerArchivo = new BufferedReader(LecturaArchivo);
                //string que me guarda el texto por línea
                String Linea;
                //try/catch en caso que se envíe un archivo que no es el solicitado
                try 
                {
                    //la variable "Linea" adquiere el valor de la primera línea del archivo
                    Linea=LeerArchivo.readLine();
                    //se crea otro string donde se va a almacenar el texto por cada línea del archivo
                    int contador = 0; 
                    //ciclo para leer linea por linea el archivo, mientras que la linea no sea null (no haya llegado al final del archivo), se repetirá el ciclo
                    while(Linea != null)
                    {
                        //si en la línea hay texto, se escribe
                        if(!"".equals(Linea))
                        {
                            //se cuenta cada línea
                            contador++;
                        }
                        //pasa a la siguiente línea para que el ciclo continue 
                        Linea=LeerArchivo.readLine();
                    }
                    //se cierra el archivo
                    LecturaArchivo.close();
                    //se termina de leer
                    LeerArchivo.close();
                    //no habrá mensaje de error
                    strError="";
                    //se envía la cantidad de objetos que hay
                    return contador;
                }
                //catch para mostrar el mensaje de error
                catch (IOException ex) 
                {
                    //mensaje de error
                    strError= ex.getMessage();
                    //la lista se retorna nula
                    return -1;
                }
            } 
            //catch para mostrar el mensaje de error
            catch (FileNotFoundException ex) 
            {
                //mensaje de error
                strError= ex.getMessage();
                //la lista se retorna nula
                return -1;
            }            
        }
        //si el archivo no se encuentra en la ruta indicada, se muestra un mensaje de error y la lista que se envía estará vacía
        else
        {
            //mensaje de error
            strError="No existe el archivo";
            //lista nula
            return -1;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MENU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelFoto;
    private javax.swing.JButton botonCambio;
    private javax.swing.JButton botonFoto;
    private javax.swing.JButton botonFoto1;
    private javax.swing.JButton botonListo;
    private javax.swing.JButton btnborrarusuario;
    private javax.swing.JButton btncerrarsesion;
    private javax.swing.JButton btnhaceradmin;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelApellido;
    private javax.swing.JLabel labelCorreo;
    private javax.swing.JLabel labelEstado;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelNum;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JTextPane textBoxApellido;
    private javax.swing.JTextPane textBoxCambioCorreo;
    private javax.swing.JTextPane textBoxCambioFecha;
    private javax.swing.JTextPane textBoxCambioRutaFoto;
    private javax.swing.JTextPane textBoxCambioTelefono;
    private javax.swing.JTextPane textBoxCambioUsuario;
    private javax.swing.JTextPane textBoxContraseña;
    private javax.swing.JTextPane textBoxCorreo;
    private javax.swing.JTextPane textBoxFecha;
    private javax.swing.JTextPane textBoxNombre;
    private javax.swing.JTextPane textBoxRutaFoto;
    private javax.swing.JTextPane textBoxTelefono;
    private javax.swing.JTextPane textBoxUsuario;
    private javax.swing.JTextPane txtadminusuario;
    private javax.swing.JTextPane txtborrarusuario;
    // End of variables declaration//GEN-END:variables
}
